### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by fengmao31** [xk-huang/yet-another-vectornet#36]
```
Traceback (most recent call last):
  File "test_and_generate_H5.py", line 96, in <module>
    test_data = GraphDataset(TEST_DIR)
  File "/home/fengmao/yet-another-vectornet/dataset.py", line 56, in __init__
    super(GraphDataset, self).__init__(root, transform, pre_transform)
  File "/home/fengmao/miniconda3/envs/myenv/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 81, in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log,
  File "/home/fengmao/miniconda3/envs/myenv/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 115, in __init__
    self._process()
  File "/home/fengmao/miniconda3/envs/myenv/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 262, in _process
    self.process()
  File "/home/fengmao/yet-another-vectornet/dataset.py", line 120, in process
    padd_to_index = np.max(valid_len_ls)
  File "<__array_function__ internals>", line 5, in amax
  File "/home/fengmao/miniconda3/envs/myenv/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/home/fengmao/miniconda3/envs/myenv/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

```

**Comment by fengmao31** [comment]
test address is wrong.
